import { Fragment } from 'react';
import Head from 'next/head'
import LogoArea from '../components/logo-area';
import MainPaperWindow from '../components/main-paper-window';
import Footer from '../components/footer';
import TokenDropdown from '../components/token-dropdown';
import Columns from '../components/columns';

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainPaperWindow>
        <LogoArea />
        <Columns className="-ml-5 -mr-5 border-b border-black">
          <Columns.Col>
            <div className="p-5 hover:bg-purple-500">
              <a href="https://nextjs.org/docs" >
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </div>
          </Columns.Col>
          <Columns.Col>
            <div className="p-5 hover:bg-purple-500">
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Columns.Col>
        </Columns>
        <Columns className="-ml-5 -mr-5 border-b border-black">
          <Columns.Col>
          <TokenDropdown />
          <p>Some instruction</p>
          </Columns.Col>

          <Columns.Col>
          <TokenDropdown />
          <p>Some instruction</p>
          </Columns.Col>
          <Columns.Col>
          <TokenDropdown />
          <p>Some instruction</p>
          </Columns.Col>
        </Columns>
        <div className="-ml-5 -mr-5 p-5">
          <p>Some expanding content can go here</p>
        </div>
      </MainPaperWindow>

      <Footer />
    </Fragment>
  )
}
